import { supabase } from '@/integrations/supabase/client';
import { Database } from '@/integrations/supabase/types';

type TransactionType = Database['public']['Enums']['transaction_type'];

export interface CreateTransactionParams {
  company_id: string;
  user_id: string;
  date: string;
  type: TransactionType;
  amount: number;
  account_id: string | null;
  category_id?: string | null;
  counterparty_id?: string | null;
  description?: string | null;
  invoice_id?: string | null;
  to_account_id?: string | null;
}

// Helper to get account ID by code
async function getAccountByCode(companyId: string, code: string) {
  const { data, error } = await supabase
    .from('chart_of_accounts')
    .select('id')
    .eq('company_id', companyId)
    .eq('code', code)
    .single();

  if (error) {
    console.error(`Error fetching account code ${code}:`, error);
    return null;
  }
  return data?.id;
}

export async function createTransaction(params: CreateTransactionParams) {
  const {
    company_id,
    user_id,
    date,
    type,
    amount,
    account_id,
    category_id,
    counterparty_id,
    description,
    invoice_id,
    to_account_id
  } = params;

  // 1. Insert Transaction
  const { data: transaction, error: txError } = await supabase
    .from('transactions')
    .insert({
      company_id,
      date,
      type,
      amount,
      account_id: account_id || null,
      to_account_id: type === 'transfer' ? to_account_id || null : null,
      category_id: type !== 'transfer' ? category_id || null : null,
      counterparty_id: counterparty_id || null,
      description: description?.slice(0, 500) || null,
      invoice_id: invoice_id || null,
      created_by: user_id,
    })
    .select()
    .single();

  if (txError) throw txError;

  // 2. Get Accounting Period
  const { data: periodId, error: periodError } = await supabase.rpc('get_period_for_date', {
    _company_id: company_id,
    _date: date,
  });

  if (periodError || !periodId) {
    console.warn('Could not find accounting period for date:', date, periodError);
    // Proceeding without journal entry as we cannot link it to a period
    return transaction;
  }

  // 3. Determine Accounts for Journal Entry
  let debitAccountCode: string | null = null;
  let creditAccountCode: string | null = null;

  if (type === 'income') {
    debitAccountCode = '1030'; // Cash/Bank
    creditAccountCode = invoice_id ? '1210' : '6010'; // AR or Revenue
  } else if (type === 'expense') {
    debitAccountCode = '7210'; // Admin Expenses
    creditAccountCode = '1030'; // Cash/Bank
  } else {
    // Transfer - Skipping automatic journal entry for now
    return transaction;
  }

  // Fetch account IDs (parallel)
  const [debitAccountId, creditAccountId] = await Promise.all([
    getAccountByCode(company_id, debitAccountCode),
    getAccountByCode(company_id, creditAccountCode)
  ]);

  if (!debitAccountId || !creditAccountId) {
    console.error('Could not find required accounts for journal entry:', { debitAccountCode, creditAccountCode });
    return transaction;
  }

  // 4. Create Journal Entry
  // entry_number is required but usually auto-generated by trigger.
  // We provide a temporary unique one to satisfy the client-side constraint if any,
  // or simply rely on the trigger overriding it.
  const tempEntryNumber = `JE-${Date.now()}-${Math.floor(Math.random() * 1000)}`;

  const { data: entry, error: entryError } = await supabase
    .from('journal_entries')
    .insert({
      company_id,
      entry_number: tempEntryNumber,
      date,
      period_id: periodId,
      description: description || `Автоматическая проводка: ${type === 'income' ? 'Доход' : 'Расход'}`,
      status: 'posted',
      posted_at: new Date().toISOString(),
      posted_by: user_id,
      created_by: user_id,
    })
    .select()
    .single();

  if (entryError) {
    console.error('Error creating journal entry:', entryError);
    return transaction;
  }

  // 5. Create Journal Lines
  const lines = [
    {
      entry_id: entry.id,
      account_id: debitAccountId,
      debit: amount,
      credit: 0,
      description: description || 'Дебет',
      line_number: 1,
    },
    {
      entry_id: entry.id,
      account_id: creditAccountId,
      debit: 0,
      credit: amount,
      description: description || 'Кредит',
      line_number: 2,
    },
  ];

  const { error: linesError } = await supabase
    .from('journal_lines')
    .insert(lines);

  if (linesError) {
    console.error('Error creating journal lines:', linesError);
  }

  return transaction;
}
